language: go
sudo: required

go:
  - 1.7
  - 1.8
  - 1.9

env:
    - GO15VENDOREXPERIMENT="1"

before_install:
    - go get github.com/mattn/goveralls

script:
    - chmod u+x coverage.sh
#    - ./coverage.sh --coveralls
    - go build -o "gopt" main/main.go

jobs:
  include:
    - script: echo "Running unit tests (1)"
    - script: echo "Running unit tests (2)"
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true