language: go
sudo: required
os:
  - linux

go:
- 1.7
- 1.8
- 1.9

env:
- GO15VENDOREXPERIMENT="1"
before_install:
- go get github.com/mattn/goveralls
script:
- chmod u+x coverage.sh
- "./coverage.sh --coveralls"
- ./make.sh

deploy:
  provider: releases
  file:
      - "dist/darwin_386_gopt.zip"
      - "dist/darwin_64_gopt.zip"
      - "dist/linux_386_gopt.zip"
      - "dist/linux_64_gopt.zip"
      - "dist/windows_386_gopt.zip"
      - "dist/windows_64_gopt.zip"
  api_key:
    secure: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    tags: true
