language: go
sudo: required

go:
  - 1.7
  - 1.8

env:
    - GO15VENDOREXPERIMENT="1"

before_install:
    - go get github.com/mattn/goveralls

script:
    - chmod u+x coverage.sh
    - ./coverage.sh --coveralls
    - pwd
    - go build -o "gopt" main/main.go