language: go
sudo: required
os:
  - linux

go:
- 1.7
- 1.8
- 1.9

env:
- GO15VENDOREXPERIMENT="1"
before_install:
- go get github.com/mattn/goveralls
script:
- chmod u+x coverage.sh
- "./coverage.sh --coveralls"
- chmod u+x make.sh
- ./make.sh

jobs:
  include:
  - stage: GitHub Release
        script: echo "Deploying to GitHub releases ..."
        deploy:
          provider: releases
          file:
              - "dist/gopt_darwin_386"
              - "dist/gopt_darwin_64"
              - "dist/gopt_linux_386"
              - "dist/gopt_linux_64"
              - "dist/gopt_windows_386"
              - "dist/gopt_windows_64"
          api_key:
            secure: $GITHUB_TOKEN
          skip_cleanup: true
          on:
            tags: true
