language: go
sudo: required

go:
  - 1.7
  - 1.8
  - 1.9

env:
    - GO15VENDOREXPERIMENT="1"

before_install:
    - go get github.com/mattn/goveralls

script:
    - chmod u+x coverage.sh
    - ./coverage.sh --coveralls
    - go build -o "gopt" main/main.go

deploy:
    provider: releases
    file: "gopt"
    api_key: $GITHUB_OAUTH_TOKEN
    skip_cleanup: true
    on:
       tags: true