language: go
sudo: required
os:
  - linux

go:
- 1.7
- 1.8
- 1.9

env:
- GO15VENDOREXPERIMENT="1"
before_install:
- go get github.com/mattn/goveralls

stages:
  - Test
  - Build
  - Github Release

script:
  - chmod u+x coverage.sh
  - "./coverage.sh --coveralls"

jobs:
  include:
      - stage: Build
        if: tag IS blank
        go: 1.9
        script:
         - echo "Build apps ..."
         - chmod u+x make.sh
         - ./make.sh
         - echo "DEPLOY_TOKEN"
         - echo $DEPLOY_TOKEN
         - echo "RELEASE_TOKEN"
         - echo $RELEASE_TOKEN
      - stage: Github Release
        if: tag =~ ^v
        go: 1.9
        script:
        - echo "Deploying to GitHub releases ..."
        - chmod u+x make.sh
        - ./make.sh
        deploy:
          provider: releases
          file_glob: true
          file: directory/*
          api_key:
            secure: $DEPLOY_TOKEN
          skip_cleanup: true
          on:
            tags: true
